CREATE TABLE submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_name TEXT,
  problem_id INTEGER,
  code TEXT,
  language TEXT,
  status TEXT,
  score INTEGER
);

-- Enable Row Level Security
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;

-- Create policies to allow all operations for this challenge (or customize as needed)
CREATE POLICY "Allow public read access"
  ON submissions FOR SELECT
  USING (true);

CREATE POLICY "Allow public insert access"
  ON submissions FOR INSERT
  WITH CHECK (true);
